[package]
name = "haze"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
bollard = { version = "0.10", git = "https://github.com/icewind1991/bollard", branch = "exec-input" }
color-eyre = "0.5"
min-id = "0.1"
maplit = "1"
camino = "1"
tokio = { version = "1" , features = ["fs", "macros"] }
parse-display = "0.4"
futures-util = "0.3"
termion = "1"