[package]
name = "haze"
version = "1.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
repository = "https://github.com/icewind1991/haze"
license = "MIT"
description = "Easy setup and management of Nextcloud test instances using docker"

[dependencies]
bollard = "0.13.0"
maplit = "1.0.2"
camino = { version = "1.0.9", features = ["serde1"] }
tokio = { version = "1.20.0", features = ["fs", "macros"] }
parse-display = "0.5.5"
futures-util = "0.3.21"
termion = "1.5.6"
opener = "0.5.0"
toml = "0.5.9"
directories-next = "2.0.0"
serde = "1.0.140"
petname = "1.1.2"
reqwest = { version = "0.11.11", default-features = false }
tar = "0.4.38"
flate2 = "1.0.24"
async-trait = "0.1.56"
enum_dispatch = "0.3.8"
miette = { version = "5.1.1", features = ["fancy"] }
shell-words = "1.1.0"

[profile.release]
lto = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/haze.{ format }"
bin-dir = "{ bin }{ format }"
