[package]
name = "haze"
version = "1.2.1"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
repository = "https://github.com/icewind1991/haze"
license = "MIT"
description = "Easy setup and management of Nextcloud test instances using docker"

[dependencies]
bollard = "0.13.0"
maplit = "1.0.2"
camino = { version = "1.1.3", features = ["serde1"] }
tokio = { version = "1.25.0", features = ["fs", "macros", "signal"] }
parse-display = "0.8.0"
futures-util = "0.3.26"
termion = "2.0.1"
opener = "0.5.2"
toml = "0.7.2"
directories-next = "2.0.0"
serde = "1.0.152"
petname = "1.1.3"
reqwest = { version = "0.11.14", default-features = false }
tar = "0.4.38"
flate2 = "1.0.25"
async-trait = "0.1.64"
enum_dispatch = "0.3.11"
miette = { version = "5.5.0", features = ["fancy"] }
shell-words = "1.1.0"
warp = "0.3"
tokio-stream = { version = "0.1.12", features = ["net"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
hyper-reverse-proxy = { version = "0.5.2-dev", git = "https://github.com/felipenoris/hyper-reverse-proxy" }
hyper = "0.14.24"
atty = "0.2.14"

[profile.release]
lto = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/haze.{ format }"
bin-dir = "{ bin }{ format }"
