[package]
name = "haze"
version = "1.0.1"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
repository = "https://github.com/icewind1991/haze"
license = "MIT"
description = "Easy setup and management of Nextcloud test instances using docker"

[dependencies]
bollard = { version = "0.11" }
maplit = "1"
camino = { version = "1", features = ["serde1"] }
tokio = { version = "1" , features = ["fs", "macros"] }
parse-display = "0.5"
futures-util = "0.3"
termion = "1"
opener = "0.5"
toml = "0.5"
directories-next = "2"
serde = "1"
petname = "1"
reqwest = { version = "0.11", default-features = false }
tar = "0.4"
flate2 = "1"
async-trait = "0.1"
enum_dispatch = "0.3"
miette = { version = "3", features = ["fancy"] }

[profile.release]
lto = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/haze.{ format }"
bin-dir = "{ bin }{ format }"