	'objectstore' => [
	  'default' => [
      'class' => 'OC\Files\ObjectStore\S3',
      'arguments' => [
        'multibucket' => true,
        'num_buckets' => 64,
        'bucket' => 'nextcloud-',
        'autocreate' => true,
        'key'    => 'dummy',
        'secret' => 'dummyj',
        'hostname' => 's3',
        'port' => 4566,
        'use_ssl' => false,
        'use_path_style' => true,
        'uploadPartSize' => 52428800,
      ],
    ],
	  'root' => [
      'class' => 'OC\Files\ObjectStore\S3',
      'arguments' => [
        'bucket' => 'nextcloud-root',
        'autocreate' => true,
        'key'    => 'dummy',
        'secret' => 'asd',
        'hostname' => 's3',
        'port' => 4566,
        'use_ssl' => false,
        'use_path_style' => true,
        'uploadPartSize' => 52428800,
      ],
    ],
	],
