	'objectstore_multibucket' => [
		'class' => 'OC\Files\ObjectStore\S3',
		'arguments' => [
		    'num_buckets' => 64,
			'bucket' => 'nextcloud-',
			'autocreate' => true,
			'key'    => 'minio',
			'secret' => 'minio123',
			'hostname' => 's3',
			'port' => 9000,
			'use_ssl' => false,
			'use_path_style' => true,
			'uploadPartSize' => 52428800,
		],
	],
