#!/bin/bash

SQL=$1
PHP_VERSION=$2

shift
shift

echo "Starting servers"
CONTAINERS=`ncserver $SQL $PHP_VERSION | tail -2 | head -1`

IFS=',' read -a CONTAINERS <<< "$CONTAINERS"

echo "Waiting for things to settle"
if [ "$SQL" = "" ] || [ "$SQL" = "sqlite" ]; then
	sleep 2 # less servers to wait for
elif [ "$SQL" = "oci" ]; then
	sleep 30 # oracle is always a bit lazy
else
	sleep 15
fi

echo "Installing"
docker exec ${CONTAINERS[0]} install admin admin

echo "Starting tests"
docker exec -t ${CONTAINERS[0]} integration $@

echo "Cleaning up"

docker kill ${CONTAINERS[0]} ${CONTAINERS[1]}
docker rm ${CONTAINERS[0]} ${CONTAINERS[1]}
