name: Release

on:
  release:
    types: [created]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - id: set-matrix
        run: echo "matrix={\"target\":$(nix eval --json ".#releaseTargets")}" | tee $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: "${{ secrets.ATTIC_TOKEN }}"
      - run: nix build .#${{ matrix.target }}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: result/bin/haze
          asset_name: haze-${{ matrix.target }}
          tag: ${{ github.ref }}
